apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-vservice
spec:
  hosts:
  - "igdemo.tbddev.org"
  gateways:
  - istio-system/primary-gateway
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: nginx-service