apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todo-vservice
spec:
  hosts:
  - {{ .Values.istio.host }}
  gateways:
  - {{ .Values.istio.gateway }}
  http:
  - route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: todo-service
